### ISSUE TITLE
How to use this program?

### ISSUE THREAD

**Issue by ATXLtheAxolotl** [CheeseInTheDark/IPXTunnel#1]
Hello! How would I run this program? I’m interested in using it for Warcraft 2 with my friends. I know I may be 8 years late but hopefully you’ll still see this.

**Comment by CheeseInTheDark** [comment]
Hi there!  Unfortunately this is not in a usable state right now.  If you search through the commit history there is a point where it is, however I can't remember the commit you'd need.  Additionally, this will not work for all operating systems, because even in its working state it makes incorrect assumption about which network interface is the correct one to use.  Not only that, but it will not work if there are multiple people on one network.

That said, if you want to try to use this, it's meant to work with this: http://www.solemnwarning.net/ipxwrapper/

Then to run it, you'll first need to install gradle: https://gradle.org/install/

Then you can run `gradle build`

Finally, find where the jar was output from the build, and from that place, run `java -jar IPXTunnelServer.jar 213 7333 7334` assuming that your IPXWrapper port is 213, I think.

You'll need to forward ports 7333 and 7334 to your computer.  You can change the ports to be whatever you like.

Next you'll need to send IPXTunnelClient.jar to your friends.  They'll run

`java -jar IPXTunnelClient.jar 213 7333 7334 [your server's public IP address] 0`

You might need to do that as well, I forget if the server also acts as a client.  I believe the `0` arg is the index of the network interface to use, but I'm not sure.  It may be possible to get around the network interface problem I mentioned earlier by changing that value.

Your friends may also need to forward ports.

The better solution than using this though is to get ipxwrapper set up on your and your friends' computers, and then set up a VPN and have everyone join it.  I haven't personally used it, but I believe this will work for that: https://vpn.net/ .  a VPN basically sets things up so your two computers see each other as being on the same network, which is what IPX needs to work.

Let me know if you have any questions, and good luck.

**Comment by ATXLtheAxolotl** [comment]
Thanks! I'll look into it
